### ISSUE TITLE
script/setup ruby version issue

### ISSUE THREAD

**Issue by mediocretes** [Instrumental/instrumental_agent-ruby#58]
./script/setup may fail to run `bundle install` due to a ruby version not being selected.  We should either add a .ruby-version (but still maintain compatibility with several versions), or make ./script/setup prompt the user to pick a version (or just pick one for them).

**Comment by jqr** [comment]
This repo is intended to be used and compatible with multiple Ruby versions, so I feel like forcing a particular Ruby version is unnecessary. I can see the case for being able to easily test against all supported versions. Basically something like [appraisal](https://github.com/thoughtbot/appraisal) but for Ruby versions.

**Comment by mediocretes** [comment]
I don't disagree with anything that you said, but I think that the output of script/setup should be a working repository, or an almost-working repository an explanation of the steps remaining.  People using system ruby are likely to have a bad time under the current system.

If we're going to remain truly unopinionated about the state of ruby on the person's system, we should remove all of the rbenv stuff (and I don't think we should do that).

I think that we can select a default ruby during setup (or point out that they probably want to select one) without forcing a particular ruby on people.
